sudo: required

branches:
  only:
  - master

cache:
  directories:
# - src
# - AUR-repo

services:
- docker

archlinux:
# repos:
# - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
  # arch/aur packages
# - python
# - perl
  script:
  - "makepkg -s --noconfirm"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- "ls $(pwd)"

deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    branch: master
  skip_cleanup: true
